"""empty message

Revision ID: 9f1a397250d0
Revises: ecc3dbdf0b8d
Create Date: 2023-06-18 21:12:17.766171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1a397250d0'
down_revision = 'ecc3dbdf0b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
